config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#login', as: :login
  post '/login' => 'sessions#set'
  get '/logout' => 'sessions#logout', as: :logout

  get 'users/new' => 'users#new', as: :new_user
  post 'users/' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  get '/admin' => 'admin#index', as: :admin
  get '/admin/posts' => 'admin#posts'
  get '/admin/post_types' => 'admin#post_types'
  get '/admin/users' => 'admin#users'
  get '/admin/images' => 'admin#images'

  resources :posts
  get '/posts/:id/status' => 'posts#switch'
  resources :post_types
  resources :images

end

app/models/image.rb
class Image
	include Mongoid::Document
	include Mongoid::Timestamps
	field :title, type: String
	field :caption, type: String
	field :author
	mount_uploader :file, ImageUploader, type: String
end

app/models/post.rb
class Post
	include Mongoid::Document
	include Mongoid::Timestamps
	include Mongoid::Attributes::Dynamic
	field :title, type: String
	field :type, type: String
	field :author
	field :published, type: Boolean, default: false

	def method_missing(method_sym, *arguments, &block)
		puts "Method: #{method_sym} is missing."
	end
end

app/models/post_type.rb
class PostType
	include Mongoid::Document
	include Mongoid::Timestamps
	field :name, type: String
	field :plural_name, type: String
	field :aspects, type: Hash, default: {}
	before_create :add_plural

	def add_plural
		self.plural_name = self.name.pluralize(2)
	end
end

app/models/user.rb
class User
	include Mongoid::Document
	include Mongoid::Timestamps
	field :name, type: String
	field :email, type: String
	field :rights, type: String
	field :password_digest, type: String

	def authenticate(password)
		self.password == password
	end

	def password
		@password ||= BCrypt::Password.new(password_digest)
	end

	def password=(pass)
		@password = BCrypt::Password.create(pass)
		self.password_digest = @password
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout "admin"
	before_filter :load_post_types

	def load_post_types
		@post_types = PostType.all
	end

	def index
		redirect_to login_path unless logged_in?
	end

	def posts
		posts = Post.all
		render json: posts
	end

	def images
		images = Image.all
		render json: images
	end

	def post_types
		post_types = PostType.all
		render json: post_types
	end

	def users
		users = User.all
		render json: {current: current_user, all: users}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def create
		image = Image.new(image_params)

		if image.save
			render json: image
		else
			render json: {title: "Error!"}
		end
	end

	def update
		image = Image.find(params[:id])
		image_params.delete("_id")
		if image.update(image_params)
			render json: image
		else
			render json: {success: false}
		end
	end

	def destroy
		image = Image.find(params[:id])
		if image.destroy
			render json: {success: true, id: params[:id]}
		else
			render json: {success: false, id: params[:id]}
		end
	end

	private

	def image_params
		params.require(:image).permit(:title, :caption, :file)
	end
end

app/controllers/post_types_controller.rb
class PostTypesController < ApplicationController

	def create
		fields = {}
		post_type_params["aspects"].each do |aspect|
			fields[aspect["name"].downcase] = aspect["type"]
		end
		fields["title"] = "text"
		type = PostType.new(name: post_type_params["name"].downcase, aspects: fields)
		if type.save
			render json: type
		else
			render json: {success: false}
		end
	end

	def update
		post_type = PostType.find(params[:id])
		post_type_params.delete("_id")
		fields = {}
		post_type_params["aspects"].each do |aspect|
			fields[aspect["name"].downcase] = aspect["type"]
		end
		if post_type.update(name: post_type_params["name"].downcase, aspects: fields)
			render json: post_type
		else
			render json: {success: false}
		end
	end

	def destroy
		post_type = PostType.find(params[:id])
		if post_type.destroy
			render json: {success: true, id: params[:id]}
		else
			render json: {success: false, id: params[:id]}
		end
	end

	private

	def post_type_params
		params.require(:post_type).permit!
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		post = Post.new(post_params)

		if post.save
			render json: post
		else
			render json: {title: "Error!"}
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def update
		post = Post.find(params[:id])
		post_params.delete("_id")
		if post.update(post_params)
			render json: post
		else
			render json: {success: false}
		end
	end

	def switch
		post = Post.find(params[:id])
		if post.update(published: post_params["published"])
			render json: post
		else
			render json: {success: false}
		end
	end

	def destroy
		post = Post.find(params[:id])
		if post.destroy
			render json: {success: true, id: params[:id]}
		else
			render json: {success: false, id: params[:id]}
		end
	end

	private

	def post_params
		params.require(:post).permit!
		# params.require(:post).permit(:title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def login
		redirect_to admin_path if logged_in?
		@user = User.new
	end

	def logout
		sign_out
		redirect_to '/'
	end

	def set
		@user = User.find_by(email: params[:email])

		if @user && @user.authenticate(params[:password])
			status = true
		else
			status = false
		end

		respond_to do |format|
			format.js {
				if status
					sign_in @user
					render json: admin_path.to_json
				else
					render json: false.to_json
				end
			}
			format.html {
				if status
					sign_in @user
					redirect_to admin_path
				else
					flash.now[:error] = "Email or password not found."
					render :login
				end
			}
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		user = User.new(new_user_params)
		if user.save
			render json: user
		else
			render json: {title: "Error!"}
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		update_user_params.delete("_id")

		if user.update(update_user_params)
			render json: user
		else
			render json: {success: false}
		end
	end

	def destroy
		user = User.find(params[:id])
		if user.destroy
			render json: {success: true, id: params[:id]}
		else
			render json: {success: false, id: params[:id]}
		end
	end

	private

	def update_user_params
		params.require(:user).permit(:name, :email, :rights)
	end

	def new_user_params
		params.require(:user).permit(:name, :email, :password, :rights)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.where(published: true)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		session[:user_id] = user.id.to_s
	end

	def sign_out
		session.delete(:user_id)
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end

	def current_user=(user)
		@current_user = user
	end

	def logged_in?
		!current_user.nil?
	end
end

app/views/admin/index.html.erb
<div id="admin-bar" ng-controller="AdminBarController">
  <% if logged_in? %>
    <div id="logged-in-bar">
      <%= link_to '<div class="rr-logo"></div>'.html_safe, admin_path %>
    </div>
  <% end %>
  <%= link_to "<div class='intro hover-background-colored'>Hello, #{current_user.name}</div>".html_safe, edit_user_path(current_user) %>
  <ul class="no-style">
    <%= link_to '<li class="hover-background-colored"><span class="icon">&#8962;</span>Visit Site</li>'.html_safe, root_path %>
    <li ng-repeat="post_type in post_types" ng-click="viewPosts(post_type.id)" class='hover-background-colored'><span class='icon'>&#9998;</span>{{ post_type.plural_name | capitalize }}</li>
    <li ng-click="viewMedia()" class='hover-background-colored'><span class='icon'>&#128193;</span>Media</li>
    <li ng-click="viewSettings()" class='hover-background-colored'><span class='icon'>&#9881;</span>Settings</li>
    <%= link_to '<li class="hover-background-colored"><span class="icon">&#59201;</span>Logout</li>'.html_safe, logout_path %>
  </ul>
</div>
<div class="admin-container" ng-view>
</div>

app/views/layouts/_logged_in_bar.html.erb
<% if logged_in? %>
  <div id="logged-in-bar">
    <%= link_to '<div class="rr-logo"></div>'.html_safe, admin_path %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html ng-app="Admin">
  <head>
    <title>Railroad</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="mobile-menu-icon"></div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railroad</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render template: "layouts/_logged_in_bar" %>
    <%= yield %>
  </body>
</html>

app/views/posts/show.html.erb
<div class="container">
  <h1 class="post-title"><%= @post.title %></h1>
  <div class="post-body">
    <%= @post.body %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h3>Edit User</h3>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %>
          prohibited
      this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :name, placeholder: 'Name' %>
    <%= f.text_field :email, placeholder: 'Email' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h3>New User</h3>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %>
          prohibited
      this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.text_field :name, placeholder: 'Name' %>
    <%= f.text_field :email, placeholder: 'Email' %>
    <%= f.password_field :password, placeholder: 'Password' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  Welcome to Railroad.
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to "#{post.title}", post %></li>
    <% end %>
  </ul>
</div>